server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:tweetlitedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN:YOUR_AUTH0_DOMAIN}/
          audiences: ${AUTH0_AUDIENCE:YOUR_AUTH0_AUDIENCE}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

auth0:
  domain: ${AUTH0_DOMAIN:YOUR_AUTH0_DOMAIN}
  audience: ${AUTH0_AUDIENCE:YOUR_AUTH0_AUDIENCE}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://YOUR_S3_BUCKET_URL}